import type { CreateMovieInput, MovieItem } from '@/types/movie';

export const movieToInput = (movie: MovieItem): CreateMovieInput => ({
  type: movie.type,
  originalTitle: movie.originalTitle,
  spanishTitle: movie.spanishTitle,
  year: movie.year,
  synopsis: movie.synopsis,
  durationMinutes: movie.durationMinutes,
  seasons: movie.seasons,
  totalEpisodes: movie.totalEpisodes,
  watched: movie.watched,
  favorite: movie.favorite,
  personalRating: movie.personalRating,
  imdbRating: movie.imdbRating,
  tmdbId: movie.tmdbId,
  imdbId: movie.imdbId,
  imdbUrl: movie.imdbUrl,
  filmaffinityUrl: movie.filmaffinityUrl,
  trailerUrl: movie.trailerUrl,
  tmdbCollectionId: movie.tmdbCollectionId,
  tmdbCollectionName: movie.tmdbCollectionName,
  images: movie.images.map((item, order) => ({ url: item.url, localPath: item.localPath, tmdbFilePath: item.tmdbFilePath, order, isPrimary: order === 0, altText: item.altText })),
  countries: movie.countries.map((item, order) => ({ name: item.name, isoCode: item.isoCode, order })),
  credits: movie.credits.map((item, order) => ({ name: item.name, creditType: item.creditType, order, characterName: item.characterName, tmdbPersonId: item.tmdbPersonId, tmdbCreditId: item.tmdbCreditId, profilePath: item.profilePath })),
  genres: movie.genres.map((item, order) => ({ name: item.name, tmdbGenreId: item.tmdbGenreId, tmdbMediaType: item.tmdbMediaType, order })),
  keywords: movie.keywords.map((item, order) => ({ name: item.name, tmdbKeywordId: item.tmdbKeywordId, order })),
  platforms: movie.platforms.map((item, order) => ({ name: item.name, tmdbProviderId: item.tmdbProviderId, logoPath: item.logoPath, order, isPrimary: order === 0 })),
  collectionIds: movie.collections.map((item) => item.id),
});
